//
// Generated file, do not edit! Created by nedtool 5.7 from Job.msg.
//

#ifndef __JOB_M_H
#define __JOB_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Job.msg:1</tt> by nedtool.
 * <pre>
 * packet Job
 * {
 *     bool isHighPriority;
 *     simtime_t queueArrival;
 *     simtime_t serviceTime;
 * }
 * </pre>
 */
class Job : public ::omnetpp::cPacket
{
  protected:
    bool isHighPriority;
    ::omnetpp::simtime_t queueArrival;
    ::omnetpp::simtime_t serviceTime;

  private:
    void copy(const Job& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Job&);

  public:
    Job(const char *name=nullptr, short kind=0);
    Job(const Job& other);
    virtual ~Job();
    Job& operator=(const Job& other);
    virtual Job *dup() const override {return new Job(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual bool getIsHighPriority() const;
    virtual void setIsHighPriority(bool isHighPriority);
    virtual ::omnetpp::simtime_t getQueueArrival() const;
    virtual void setQueueArrival(::omnetpp::simtime_t queueArrival);
    virtual ::omnetpp::simtime_t getServiceTime() const;
    virtual void setServiceTime(::omnetpp::simtime_t serviceTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Job& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Job& obj) {obj.parsimUnpack(b);}


#endif // ifndef __JOB_M_H

