//
// Generated file, do not edit! Created by opp_msgtool 6.0 from Job.msg.
//

#ifndef __JOB_M_H
#define __JOB_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Job;
/**
 * Class generated from <tt>Job.msg:1</tt> by opp_msgtool.
 * <pre>
 * packet Job
 * {
 *     bool isHighPriority;
 *     simtime_t queueArrival;		//il momento in cui arrivano nella queue
 *     simtime_t serviceTime;		//per simulare il fatto che ogni job richiede del tempo per essere servito, quando arriva allo scheduler lo facciamo aspettare per questo tot tempo prima di eliminare il job
 *     simtime_t processingTime; 	//timestamp in cui il job viene servito dallo scheduler
 * }
 * </pre>
 */
class Job : public ::omnetpp::cPacket
{
  protected:
    bool isHighPriority_ = false;
    omnetpp::simtime_t queueArrival = SIMTIME_ZERO;
    omnetpp::simtime_t serviceTime = SIMTIME_ZERO;
    omnetpp::simtime_t processingTime = SIMTIME_ZERO;

  private:
    void copy(const Job& other);

  protected:
    bool operator==(const Job&) = delete;

  public:
    Job(const char *name=nullptr, short kind=0);
    Job(const Job& other);
    virtual ~Job();
    Job& operator=(const Job& other);
    virtual Job *dup() const override {return new Job(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual bool isHighPriority() const;
    virtual void setIsHighPriority(bool isHighPriority);

    virtual omnetpp::simtime_t getQueueArrival() const;
    virtual void setQueueArrival(omnetpp::simtime_t queueArrival);

    virtual omnetpp::simtime_t getServiceTime() const;
    virtual void setServiceTime(omnetpp::simtime_t serviceTime);

    virtual omnetpp::simtime_t getProcessingTime() const;
    virtual void setProcessingTime(omnetpp::simtime_t processingTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Job& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Job& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Job *fromAnyPtr(any_ptr ptr) { return check_and_cast<Job*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __JOB_M_H

